# Generated by Django 5.0.2 on 2024-03-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fiends_with',
            field=models.ManyToManyField(related_name='friends', to='Go.user'),
        ),
    ]
