# Generated by Django 5.0.2 on 2024-03-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0004_user_last_time_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fiends_with',
            field=models.ManyToManyField(to='Go.user'),
        ),
    ]
