# Generated by Django 5.0.2 on 2024-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0006_alter_user_fiends_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fiends_with',
            field=models.ManyToManyField(blank=True, related_name='fiends', to='Go.user'),
        ),
    ]
