# Generated by Django 5.0.2 on 2024-03-02 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0007_alter_user_fiends_with'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Player',
        ),
    ]
