# Generated by Django 5.0.2 on 2024-03-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0008_rename_user_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_type', models.CharField(choices=[('Computer', 'Computer'), ('Multiplayer', 'Multiplayer'), ('Versus', 'Versus')], max_length=11)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('board_size', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('Victory', 'Victory'), ('Loss', 'Loss'), ('Tie', 'Tie')], max_length=7)),
                ('duration', models.DateTimeField(blank=True, null=True)),
                ('captured_stones', models.PositiveIntegerField(blank=True, null=True)),
                ('territory_points', models.PositiveIntegerField(blank=True, null=True)),
                ('first_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Go.player')),
                ('game', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Go.game')),
            ],
        ),
    ]
