# Generated by Django 5.0.2 on 2024-03-02 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0009_game_stats'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stats',
            new_name='Statistic',
        ),
    ]
