# Generated by Django 5.0.2 on 2024-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0014_alter_player_options_alter_player_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
