# Generated by Django 5.0.2 on 2024-03-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0016_remove_player_last_time_online_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
