# Generated by Django 5.0.2 on 2024-03-04 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0017_alter_player_email_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
