# Generated by Django 5.0.2 on 2024-03-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0019_alter_player_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board_size',
            field=models.PositiveIntegerField(choices=[(19, '19'), (13, '13'), (9, '9')], default=19),
        ),
        migrations.AlterField(
            model_name='game',
            name='game_type',
            field=models.CharField(choices=[('Versus', 'Versus'), ('Computer', 'Computer'), ('Multiplayer', 'Multiplayer')], default='Versus', max_length=11),
        ),
    ]
