# Generated by Django 5.0.2 on 2024-03-04 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0021_alter_statistic_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='first_player',
            new_name='player',
        ),
    ]
