# Generated by Django 5.0.2 on 2024-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0024_alter_statistic_captured_stones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coord', models.PositiveIntegerField()),
                ('y_coord', models.PositiveIntegerField()),
                ('color', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
