# Generated by Django 5.0.2 on 2024-03-04 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0040_alter_stone_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='last_move',
            field=models.BooleanField(default=False),
        ),
    ]
