# Generated by Django 5.0.2 on 2024-03-04 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0041_statistic_last_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='last_move',
        ),
        migrations.AddField(
            model_name='statistic',
            name='last_move_color',
            field=models.BooleanField(default=True),
        ),
    ]
