# Generated by Django 5.0.2 on 2024-03-04 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0042_remove_statistic_last_move_statistic_last_move_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='last_move_color',
            new_name='last_move',
        ),
    ]
