# Generated by Django 5.0.2 on 2024-03-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0043_rename_last_move_color_statistic_last_move'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stone',
            new_name='NewStone',
        ),
    ]
