# Generated by Django 5.0.2 on 2024-03-05 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0044_rename_stone_newstone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewStone',
            new_name='Stone',
        ),
    ]
