# Generated by Django 5.0.2 on 2024-03-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0045_rename_newstone_stone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(default='guest.non_existent@mail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='Guest', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='Guest', max_length=20),
        ),
    ]
