# Generated by Django 5.0.2 on 2024-03-05 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0046_alter_player_email_alter_player_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_with_color',
            field=models.CharField(choices=[('Black', 'Black'), ('White', 'White')], default='Black', max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='player',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
    ]
