# Generated by Django 5.0.2 on 2024-03-05 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Go', '0047_game_start_with_color_alter_player_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='captured_stones',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='territory_points',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
